#%RAML 1.0 Library
uses:
  odata: libraries/odataLibrary.raml

types:
  ODemo:
    description: Example Table Exposed by OData
    (odata.remote): ODemo
    properties:
      Id:
        format: int32
        description: Primary key for ODemo
        required: false
        type: number
        (odata.key): true
        (odata.nullable): false
      Name:
        type: string
        description: Name of ODemo Record
        (odata.key): false
        (odata.nullable): false
